/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js projects and kept in source so TypeScript
// has the expected ambient types before the first local dev run.
